### ISSUE TITLE
Converting this project into a crate

### ISSUE THREAD

**Issue by IamTheCarl** [crawfxrd/gba-dev-rs#1]
Hello. I got this project to build and run in my emulator.
Now I'm converting it into a crate that you can import into your project to quickly spin up a GBA application. So far this is going well.
It's pretty similar to how the cortex-m-rt crate is used.

Currently it just provides a linker script and generates the proper header in the .text section.
I plan to add the ability to tag the main function and interrupt handlers.
A more far off feature is the ability to customize the header section to accurately reflect the name of your application.

I'd like to properly credit you, especially since the majority of it is still your work.
My plan was to keep the original licenses in there.
I would include a link to this repo in the readme.
I can't seem to find any copyrights in here, so I don't plan to add a copyright of my own ether.

Is this enough for your liking?

**Comment by Lokathor** [comment]
note: there's a version of `gbafix` available on crates.io, for post-build header fixups

**Comment by IamTheCarl** [comment]
I don't know how I missed all the copyrights in the source files themselves.
So I'll probably put my copyright below yours in those cases.

Also I have the entry tag feature working.

**Comment by crawfxrd** [comment]
Fundamental files for building in this project are CC-0, requiring no copyright attribution and can be relicensed to whatever you want. The MPL licensed code is either trivial enough that you would end up writing it yourself anyway, even if not using this project, or bad enough that you should rewrite it anyway.

@Lokathor's projects should be used instead, as he actively develops tools, libraries, and documentation for using Rust for GBA development.
